# Generated by Django 5.2.1 on 2025-05-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField()),
                ('cca2', models.CharField(max_length=2, unique=True)),
                ('cca3', models.CharField(max_length=3, unique=True)),
                ('ccn3', models.CharField(blank=True, max_length=3, null=True)),
                ('independent', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
                ('unMember', models.BooleanField(default=False)),
                ('currencies', models.JSONField(blank=True, null=True)),
                ('capital', models.JSONField(blank=True, null=True)),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.JSONField(blank=True, null=True)),
                ('translations', models.JSONField(blank=True, null=True)),
                ('latlng', models.JSONField(blank=True, null=True)),
                ('landlocked', models.BooleanField(default=False)),
                ('borders', models.JSONField(blank=True, null=True)),
                ('area', models.FloatField()),
                ('demonyms', models.JSONField(blank=True, null=True)),
                ('flag', models.CharField(max_length=10)),
                ('maps', models.JSONField(blank=True, null=True)),
                ('population', models.BigIntegerField()),
                ('gini', models.JSONField(blank=True, null=True)),
                ('timezones', models.JSONField()),
                ('continents', models.JSONField()),
                ('flags', models.JSONField()),
                ('coatOfArms', models.JSONField(blank=True, null=True)),
                ('startOfWeek', models.CharField(max_length=20)),
                ('capitalInfo', models.JSONField(blank=True, null=True)),
                ('postalCode', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
